- name: Ansible Jobs Create
  hosts: localhost
  tasks:
    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: test1
        password: admin123
        url: http://172.31.46.122:8080
        user: admin1

