- name: Ansible Jobs Create
  hosts: localhost
  tasks:
    - name: create jenkins jobs - Frontend
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: frontend
        password: admin123
        url: http://172.31.46.122:8080
        user: admin1

    - name: create jenkins jobs - Backend
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: backend
        password: admin123
        url: http://172.31.46.122:8080
        user: admin1

    - name: create jenkins jobs - Expense Parameters
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: expense-parameters
        password: admin123
        url: http://172.31.46.122:8080
        user: admin1

    - name: create jenkins jobs - Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: expense-terraform
        password: admin123
        url: http://172.31.46.122:8080
        user: admin1
